[project]
name = 'POSVault'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.governance-token]
path = 'contracts/governance-token.clar'
clarity_version = 3
epoch = 'latest'

[contracts.vault-core]
path = 'contracts/vault-core.clar'
clarity_version = 3
epoch = 'latest'

[contracts.proposal-voting]
path = 'contracts/proposal-voting.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
